Repository maistra/api, pull requests merged in 2021-06, with the labels that each got.

#6 MAISTRA-2351: Bump CRDs to apiextensions.k8s.io/v1
  Makefile
  manifests/maistra.io_federationstatuses.yaml
  manifests/maistra.io_meshfederations.yaml
  manifests/maistra.io_serviceexports.yaml
  manifests/maistra.io_serviceimports.yaml
  manifests/maistra.io_servicemeshcontrolplanes.yaml
  manifests/maistra.io_servicemeshextensions.yaml
  manifests/maistra.io_servicemeshmemberrolls.yaml
  manifests/maistra.io_servicemeshmembers.yaml
Labels: okay to merge, size/XXL

#13 Revert "MAISTRA-2351: Bump CRDs to apiextensions.k8s.io/v1"
  Makefile
  manifests/maistra.io_federationstatuses.yaml
  manifests/maistra.io_meshfederations.yaml
  manifests/maistra.io_serviceexports.yaml
  manifests/maistra.io_serviceimports.yaml
  manifests/maistra.io_servicemeshcontrolplanes.yaml
  manifests/maistra.io_servicemeshextensions.yaml
  manifests/maistra.io_servicemeshmemberrolls.yaml
  manifests/maistra.io_servicemeshmembers.yaml
Labels: okay to merge, size/XXL

#14 MAISTRA-2251: Add the Message field to SME deployment status
  core/v1/extension_types.go
  core/v1alpha1/conversion_generated.go
  core/v1alpha1/extension_types.go
  manifests/maistra.io_servicemeshextensions.yaml
Labels: okay to merge, size/S

#17 MAISTRA-2425 move MeshFederation CertificateChain to ConfigMap refere…
  core/v1/meshfederation_types.go
  core/v1/zz_generated.deepcopy.go
  manifests/maistra.io_meshfederations.yaml
Labels: okay to merge, size/M
