Repository maistra/api, pull requests merged in 2021-05, with the labels that each got.

#2 Fix client generation
  Makefile
Labels: okay to merge, size/S

#5 Fix the build tag, it needs a blank line
  tools.go
Labels: okay to merge, size/XS

#8 MAISTRA-2295 create CRD for federation ServiceImport
  Makefile
  client/informers/externalversions/core/v1alpha1/interface.go
  client/informers/externalversions/core/v1alpha1/serviceimports.go
  client/informers/externalversions/generic.go
  client/listers/core/v1alpha1/expansion_generated.go
  client/listers/core/v1alpha1/serviceimports.go
  client/versioned/typed/core/v1alpha1/core_client.go
  client/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  client/versioned/typed/core/v1alpha1/fake/fake_serviceimports.go
  client/versioned/typed/core/v1alpha1/generated_expansion.go
  client/versioned/typed/core/v1alpha1/serviceimports.go
  core/v1alpha1/import_export_mapping.go
  core/v1alpha1/serviceexports_types.go
  core/v1alpha1/serviceimports_types.go
  core/v1alpha1/zz_generated.deepcopy.go
  manifests/maistra.io_serviceexports.yaml
  manifests/maistra.io_serviceimports.yaml
Labels: okay to merge, size/XXL

#9 MAISTRA-2295 add ServiceImports to SchemeBuilder
  core/v1alpha1/groupversion_info.go
Labels: okay to merge, size/XS

#10 MAISTRA-2309 create CRD for FederationStatus
  client/informers/externalversions/core/v1alpha1/federationstatus.go
  client/informers/externalversions/core/v1alpha1/interface.go
  client/informers/externalversions/generic.go
  client/listers/core/v1alpha1/expansion_generated.go
  client/listers/core/v1alpha1/federationstatus.go
  client/versioned/typed/core/v1alpha1/core_client.go
  client/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  client/versioned/typed/core/v1alpha1/fake/fake_federationstatus.go
  client/versioned/typed/core/v1alpha1/federationstatus.go
  client/versioned/typed/core/v1alpha1/generated_expansion.go
  core/v1alpha1/federationstatus_types.go
  core/v1alpha1/groupversion_info.go
  core/v1alpha1/zz_generated.deepcopy.go
  manifests/maistra.io_federationstatuses.yaml
Labels: okay to merge, size/XXL
